
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.ScrolledWindow scrolledwindow2;

	private global::Gtk.Label label4;

	private global::Gtk.Button save;

	private global::Gtk.Button load;

	private global::Gtk.Button addelement;

	private global::Gtk.Button cleardata;

	private global::Gtk.Label label5;

	private global::Gtk.Button Info;

	private global::Gtk.Label currentlysel;

	private global::Gtk.Button Exporttga;

	private global::Gtk.RadioButton spritesheet;

	private global::Gtk.RadioButton cubemap;

	private global::Gtk.RadioButton animation;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 800;
		this.HeightRequest = 800;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("spritesheet manager");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow2.WidthRequest = 800;
		this.scrolledwindow2.HeightRequest = 500;
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.scrolledwindow2.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		this.fixed1.Add(this.scrolledwindow2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.scrolledwindow2]));
		w1.Y = 300;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Shadowdevs spritesheet manager");
		this.label4.UseMarkup = true;
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w2.X = 5;
		w2.Y = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.save = new global::Gtk.Button();
		this.save.CanFocus = true;
		this.save.Name = "save";
		this.save.UseUnderline = true;
		this.save.Label = global::Mono.Unix.Catalog.GetString("Save to meta");
		this.fixed1.Add(this.save);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.save]));
		w3.X = 36;
		w3.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.load = new global::Gtk.Button();
		this.load.CanFocus = true;
		this.load.Name = "load";
		this.load.UseUnderline = true;
		this.load.Label = global::Mono.Unix.Catalog.GetString("Load from meta");
		this.fixed1.Add(this.load);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.load]));
		w4.X = 165;
		w4.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.addelement = new global::Gtk.Button();
		this.addelement.CanFocus = true;
		this.addelement.Name = "addelement";
		this.addelement.UseUnderline = true;
		this.addelement.Label = global::Mono.Unix.Catalog.GetString("Add element");
		this.fixed1.Add(this.addelement);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.addelement]));
		w5.X = 37;
		w5.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cleardata = new global::Gtk.Button();
		this.cleardata.CanFocus = true;
		this.cleardata.Name = "cleardata";
		this.cleardata.UseUnderline = true;
		this.cleardata.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.fixed1.Add(this.cleardata);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cleardata]));
		w6.X = 682;
		w6.Y = 251;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("presets");
		this.fixed1.Add(this.label5);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
		w7.X = 675;
		w7.Y = 6;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Info = new global::Gtk.Button();
		this.Info.CanFocus = true;
		this.Info.Name = "Info";
		this.Info.UseUnderline = true;
		this.Info.Label = global::Mono.Unix.Catalog.GetString("Info");
		this.fixed1.Add(this.Info);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Info]));
		w8.X = 622;
		w8.Y = 251;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.currentlysel = new global::Gtk.Label();
		this.currentlysel.Name = "currentlysel";
		this.currentlysel.LabelProp = global::Mono.Unix.Catalog.GetString("currently selected");
		this.fixed1.Add(this.currentlysel);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.currentlysel]));
		w9.X = 632;
		w9.Y = 132;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Exporttga = new global::Gtk.Button();
		this.Exporttga.CanFocus = true;
		this.Exporttga.Name = "Exporttga";
		this.Exporttga.UseUnderline = true;
		this.Exporttga.Label = global::Mono.Unix.Catalog.GetString("Export to png");
		this.fixed1.Add(this.Exporttga);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Exporttga]));
		w10.X = 187;
		w10.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spritesheet = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("spritesheet"));
		this.spritesheet.CanDefault = true;
		this.spritesheet.CanFocus = true;
		this.spritesheet.Name = "spritesheet";
		this.spritesheet.DrawIndicator = true;
		this.spritesheet.UseUnderline = true;
		this.spritesheet.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this.spritesheet);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spritesheet]));
		w11.X = 641;
		w11.Y = 46;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cubemap = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("cubemap"));
		this.cubemap.CanFocus = true;
		this.cubemap.Name = "cubemap";
		this.cubemap.DrawIndicator = true;
		this.cubemap.UseUnderline = true;
		this.cubemap.Group = this.spritesheet.Group;
		this.fixed1.Add(this.cubemap);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cubemap]));
		w12.X = 645;
		w12.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.animation = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("animation"));
		this.animation.CanFocus = true;
		this.animation.Name = "animation";
		this.animation.DrawIndicator = true;
		this.animation.UseUnderline = true;
		this.animation.Group = this.spritesheet.Group;
		this.fixed1.Add(this.animation);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.animation]));
		w13.X = 646;
		w13.Y = 96;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 800;
		this.spritesheet.HasDefault = true;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.save.Clicked += new global::System.EventHandler(this.OnSaveClicked);
		this.load.Clicked += new global::System.EventHandler(this.OnLoadClicked);
		this.addelement.Clicked += new global::System.EventHandler(this.OnAddelementClicked);
		this.cleardata.Clicked += new global::System.EventHandler(this.OnCleardataClicked);
		this.Info.Clicked += new global::System.EventHandler(this.OnInfoClicked);
		this.Exporttga.Clicked += new global::System.EventHandler(this.OnExporttgaClicked);
		this.spritesheet.Toggled += new global::System.EventHandler(this.OnSpritesheetToggled);
		this.cubemap.Toggled += new global::System.EventHandler(this.OnCubemapToggled);
		this.animation.Toggled += new global::System.EventHandler(this.OnAnimationToggled);
	}
}
